[env:esp32-p4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-p4-evboard
framework = espidf
monitor_speed = 115200
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
build_flags =
  -D CAMERA_SENSOR_OV5647=1
